### ISSUE TITLE
[설계] 기능 명세서 작성

### ISSUE THREAD

**Issue by Lai-khan** [HICC-Bootcamp/2021-1-Tikkeul-Todaily#1]
서비스의 기능에 대해 설명하는 문서를 작성한다.

## 목적
- 만들고자 하는 서비스는 어떤 기능을 가지고 있는지 한눈에 알아보기 좋게 정리한다.
- 필수 기능과 선택 기능을 분리하여 정리함으로서 개발 시 더 중요한 기능에 집중할 수 있도록 한다.

## 방법
- Wiki에 기능명세서 페이지를 만들고 기능에 대해 정리한다.

다 작성하면 본 이슈에 코멘트로 링크를 달아주면 됩니다.

**Comment by Lai-khan** [comment]
# 작성 예시 (참고)
간단한 게시판 서비스
## 필수 기능
### 1. 회원관리
- 회원가입
- 로그인
- 로그아웃
### 2. 게시판 CRUD
- 글 작성
- 게시판 글 가져오기 (페이징)
- 글 수정
- 글 삭제

## 선택 기능
### 1. 회원관리
- 회원탈퇴
### 2. 게시판 CRUD
- 댓글
- 좋아요

**Comment by u-nij** [comment]
https://github.com/HICC-Bootcamp/2021-1-Tikkeul-Todaily/wiki/%EA%B8%B0%EB%8A%A5%EB%AA%85%EC%84%B8%EC%84%9C

**Comment by Lai-khan** [comment]
@u-nij 
화면은 기능이 아닙니다. 이렇게 정리하시면 서비스에 어떤 기능이 있는지 한눈에 알아보기 힘듭니다.
기획서에 있는 내용을 그냥 옮기는 게 아니라 다시 기능 단위로 정리해주세요.

**Comment by u-nij** [comment]
수정했습니다..!

**Comment by Lai-khan** [comment]
고생하셨습니다. 이슈 닫으셔도 됩니다. (`Close issue` 버튼 누르면 됩니다.)
다른 작업들도 열심히 해주세요. :)

한가지 궁금한 게 있는데요. `비밀번호 찾기`기능은 뭔가요? 이전 글을 찾아보니 비밀번호 재설정 기능을 말하는 것 같은데 만약 그렇다면 이름을 잘못 지은 것 같습니다. 기능을 제대로 나타내지 못하고 있는 것 같네요..

**Comment by u-nij** [comment]
아하.. 넵 재설정이 기능을 더 잘 나타내는 것 같아서 수정했습니다!
