### ISSUE TITLE
[설계] DB 설계

### ISSUE THREAD

**Issue by Lai-khan** [HICC-Bootcamp/2021-1-Tikkeul-Todaily#2]
서비스의 요구사항에 맞게 DB를 설계해보자.

## 들어가야 할 내용
- 사용할 DBMS
- 어떤 용도의 테이블인가 (ex. 회원 테이블)
- 테이블 명
- 컬럼의 이름
- 컬럼의 데이터 타입
- 제약
- 각 테이블 간의 관계 (간단하게 그리기 or DB 설계 도구 이용)

## 예시
- 게시판 글 테이블

| 이름 | 데이터 타입 | 제약 | 설명 |
|---|-----|---|------|
|id|INT(11)|pk, auto increment|글 ID|
|userId|VARCHAR(20)|not null|글 작성자 ID|
|title|VARCHAR(50)|not null|글 제목|
|contents|VARCHAR(200)|not null|글 내용|
|created_at|DATETIME|not null default now|생성날짜|

## 방법
Wiki 페이지에 'DB 설계' 페이지 생성해서 작성한 뒤 본 이슈에 코멘트로 링크 달면 됩니다.

**Comment by u-nij** [comment]
https://github.com/HICC-Bootcamp/2021-1-Tikkeul-Todaily/wiki/DB-%EC%84%A4%EA%B3%84

**Comment by Lai-khan** [comment]
@u-nij 
- PK는 기본적으로 unique + not null 이기 때문에 중복해서 쓰지 않아도 됩니다. 테이블 생성 SQL문을 짤 때는 위에 not null을 붙이고 밑에서 pk라고 따로 설정하긴 합니다만 표로 나타낼때는 하나만 써도 됩니다.
- 로그인할때 이메일/비번을 입력받을 건가요? 이메일에 unique가 걸려있네요. 주로 로그인 할때나 서비스에서 유저를 나타낼때 쓰는 데이터는 `username`이 될 것 같은데요. 게시판 테이블에도 유저 이름이 foreign key로 걸려있고 말이죠.
- 게시판 테이블 이름이 왜 `post`인가요? post는 개발에서 주로 요청을 보낸다는 의미로 쓰입니다. (HTTP Method. POST)
- 게시판 테이블의 `image` 칼럼의 타입이 과한 것 같네요. 설명에는 이미지 이름이라고 되어있는데, 이미지 파일명이겠죠? 암튼 그 정도면 varchar로 충분합니다.
- foreign key는 데이터 타입이 아닙니다.
- DB 칼럼 이름을 지을 때는 모두 소문자로 지어야 하고, 복합어구에는 `_`를 사용하는 것이 원칙입니다. `e-mail`, `createdAt` 수정해주세요. ([참고](https://sabarada.tistory.com/49))
- foreign key를 설정할 때는 옵션도 같이 설정해줘야 합니다. 부모키가 삭제 또는 변경되었을때 어떻게 할지 (on delete cascade, on delete set null, on update cascade) 나중에 SQL문 짤 때 참고해주세요.
- 시간 되면 미리 CREATE 문도 짜보면 좋겠네요! :)

**Comment by u-nij** [comment]
이메일 계정별로 계정을 하나만 생성시키게 하기 위해 unique를 옵션으로 넣었습니다..! 나머지는 수정했습니다!

**Comment by Lai-khan** [comment]
@u-nij 
- 회원 테이블과 로그인 테이블을 따로 두는 이유는 뭔가요? 이러면 불필요하게 데이터만 중복될 것 같은데요.
- `image` 칼럼의 데이터 타입이 그대로입니다.
- `text` 칼럼에서 not null 조건을 뺀 이유는 뭔가요? 제목만 입력하고도 게시글을 작성할 수 있나요?
- `foreign key`와 마찬가지로 `ON DELETE CASCADE, ON UPDATE CASCADE`도 데이터 타입이 아닙니다. 제약에 넣어주세요.

**Comment by Lai-khan** [comment]
> ~~게시판 테이블 이름이 왜 post인가요? post는 개발에서 주로 요청을 보낸다는 의미로 쓰입니다. (HTTP Method. POST)~~

윗 부분 코멘트 정정합니다. 생각해보니 어차피 DB 테이블이라 상관 없겠네요.

**Comment by u-nij** [comment]
- API 설계하면서 햇갈렸나봅니다.. 저도 왜 추가한지 모르겠네요..! 삭제했습니다!
- `text` 칼럼이나 `image` 칼럼 중 하나만 null일 때, 글이 생성될 수 있게 하려고 했습니다! 일단 `text`칼럼에 not null 조건 추가하고 나중에 수정하겠습니다..!
- 수정했습니다..!
- board->posts로 바꾸겠습니다..!

**Comment by u-nij** [comment]
회원 테이블 USERS
- token 칼럼 추가
