### ISSUE TITLE
[설계] API 설계

### ISSUE THREAD

**Issue by Lai-khan** [HICC-Bootcamp/2021-1-Tikkeul-Todaily#3]
'이렇게 HTTP 요청을 보내면, 이렇게 응답해준다'라는 스펙을 기능에 따라 설계한다.

HTTP에 대한 이해 필요

## 들어가야 할 내용
- HTTP Method
- URL
- Request Format
- Response Format

### 회원 목록
```
GET /users
```
### Request Data
없음
### Response Data
```
[
    {
        "userId": 사용자 ID, (string)
        "userName": 사용자 이름, (string)
        "userProfileUrl": 사용자 프로필 사진 Url (string)
    },
    . . . . . .
]
```
```json
[
    {
        "userId": "user12345",
        "userName": "람보",
        "userProfileUrl": "https://item.kakaocdn.net/do/33702f467a63bf8b9eb32adb9f539fd6617ea012db208c18f6e83b1a90a7baa7",
    },
    {
        "userId": "nanananan",
        "userName": "무무",
        "userProfileUrl": "https://item.kakaocdn.net/do/33702f467a63bf8b9eb32adb9f539fd6617ea012db208c18f6e83b1a90a7baa7",
    },
    {
        "userId": "yeah44",
        "userName": "크롱",
        "userProfileUrl": "https://item.kakaocdn.net/do/33702f467a63bf8b9eb32adb9f539fd6617ea012db208c18f6e83b1a90a7baa7",
    },
]
```
## 방법
Wiki 페이지에 'API 설계' 페이지 생성해서 작성한 뒤 본 이슈에 코멘트로 링크 달면 됩니다.

**Comment by u-nij** [comment]
https://github.com/HICC-Bootcamp/2021-1-Tikkeul-Todaily/wiki/API-%EC%84%A4%EA%B3%84

(회원가입 후, posts 테이블의 id 값이 1인 게시글이 자동 생성됩니다. 이 게시글이 `/main?username=:username/1`에서 보여집니다.)

**Comment by Lai-khan** [comment]
@u-nij 
1. API URL에 path variable과 query string이 혼재되어 있네요. 
   - `/main?username=:username/1` -> 이 URL을 보면 username은 `:username`으로 되어있는 걸로 보아 path variable인데 이 경우에는 이렇게 `username=값` 형태로 표현하지 않습니다. `?` 뒤에 `변수=값` 형태로 표현하는 것은 query string입니다. 그리고 데이터에 따라 path variable과 query string의 용도가 다릅니다.
   - path variable과 query string의 차이와 용도에 대해 찾아보고 다시 설계해보길 바랍니다.
   - 관련 부분 다 수정해주세요.
2. 로그인 API에서 token이 response data에 포함되어 있는 걸 보니 JWT를 사용해서 구현할 건가요?? 처음 회원 기능을 구현하는건데 JWT는 좀 어려울 수 있을 것 같네요.
3. (JWT로 구현한다는 가정하에) 회원가입 API에서 `token`과 `username`을 반환하는데, 혹시 이 부분에서 회원가입 요청과 **인가(Authorization)** 를 혼동하지 않았나 싶습니다. 회원가입은 새로운 유저를 만들어달라는 요청이고, 로그인 요청은 해당 유저가 회원이 맞는지 확인해달라는 **인증(Authentication)** 요청입니다.(JWT에서는 인증할 때 access token 반환해야 하니 로그인 API는 token을 반환하는게 맞습니다. 다만 access token과 refresh token은 다르니 이름을 명확히 구분하는 게 좋을 것 같네요.) 그렇기 때문에 회원가입 API에서는 `token`과 `username` 같은 데이터를 반환할 필요가 없습니다.
   - 회원 기능 구현 전에 한번 Authentication과 Authorization에 대해서 공부해보면 좋을 것 같습니다.
   - 만약 JWT로 구현하는게 아니라면 회원가입과 로그인 둘 다 반환값이 없어도 됩니다. 사실 node로 구현한다면 뭐 바로 redirect 해버릴 것 같지만요.
4. 'content 스키마'에서 스키마는 DB 구조를 가리키는 단어입니다. 용어 사용이 부적절합니다.
5. 메인화면에서 게시글을 하나만 가져오는 것 같은데, 게시글이 여러개면 가져오는 기준이 어떻게 되나요?
6. 게시글 목록 API에서 `year`와 `month`를 path variable로 받고 있는데, 이렇게 필터링에 사용되는 데이터의 경우 query string으로 받습니다. 그리고 year와 month로 받기보다는 front에서 따로 처리를 해서 startDate, endDate로 받는 게 더 깔끔해 보이네요. 어차피 DB에서 조회할 때 between 써서 조회해야 할테니까요.
7. content 구조를 보니 이미 데이터가 `{ }`로 감싸져 있고, 그게 여러 개일 경우 `[ ]`로 감싸져 있는데, 굳이 다시 `{ }`로 감쌀 필요는 없어보입니다. depth만 깊어져요.

**Comment by u-nij** [comment]
참고해서 수정해봤습니다.!
2,3. access token을 반환하는 의도였습니다..! redirect도 염두에 두겠습니다.
5. 정해놓은 메인화면 특성상 글이 1개만 있기때문에 메인화면용 DB 테이블을 새로 생성할지 고민하다가.. 회원가입을 할 때 자동으로 글이 생성되게끔 해서(메인화면용 생성 API를 따로 만들지 않은 이유입니다) 게시글 id가 1인 것을 가져오게 하려 했습니다. 이 경우에 회원가입 API response에 content(게시글)을 추가해야할까요? 혹시 다른 좋은 의견 있으시면 들려주시면 감사하겠습니다😥..

**Comment by Lai-khan** [comment]
우선 메인화면만을 위해 DB 테이블을 따로 만드는 것은 좀 아니구요.
자동으로 글이 생성되게 하는 것도 아닌것 같습니다.
회원가입할 때 content를 반환하는 것도 아니구요. API든 함수든 뭐든 기능을 설계할 때는 한번에 한가지 기능만을 수행해야 합니다. 하나의 기능이 본연의 역할에서 벗어나거나 여러 역할을 수행하는 것은 좋지 않습니다.

게시글 id가 1인것을 가져온다고 했는데, 게시글 테이블의 id는 auto_increment라서 여러 사람이 사용하게 되면 누구든 간에 가장 먼저 글을 작성한 사람의 게시글의 id가 1이 됩니다. 그러면 자신이 작성한 글이 아닌데도 모든 회원들이 엉뚱한 게시글을 메인화면에서 보게 될테고, 가장 먼저 게시글을 작성한 사람은 자신의 게시글이 다른 사람들의 메인화면에 보이게 될텐데요??

그냥 게시글을 작성하기 전까지는 메인화면은 게시글을 작성해달라는 메시지를 띄워놓고, 게시글을 하나라도 작성하면 가져오는 것으로 하는 것이 좋을 것 같습니다. 가져올 때도 id=1인 조건이 아니라 그냥 가장 최신 게시글을 가져오게 하면 매번 바뀌고 좋을 것 같네요.

**Comment by u-nij** [comment]
앗 생각해보니 DB가 그렇겠네요..!😅 왜 각자 할당된다고 생각했는지 모르겠습니다. 수정했습니다!

**Comment by Lai-khan** [comment]
@u-nij 
글을 가져오거나 수정, 삭제할 때, `username`을 URL에 같이 담아서 보내는데, 이렇게 유저의 정보가 URL에 노출되는 것은 좋지 않습니다. 그리고 불필요하다고 생각합니다. 어차피 게시글 작성 및 메인화면 등등은 로그인을 해야지만 이용할 수 있는 서비스 아닌가요? 그렇다면 로그인을 한 상태에서 이용할 테니 token에 유저 정보가 담겨있을겁니다. 서버에서 알아서 해당 정보를 가져다 사용하면 됩니다.

**Comment by Lai-khan** [comment]
`username`은 유저를 식별할 수 있는 중요정보에 해당되서 그렇지만 `username`이 아니더라도 `id` 처럼 자원을 가리키는 데이터가 아니라 필터링에 사용되는 데이터라면 query string으로 나타내는 게 맞습니다.
